### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by anselb** [GirugaCode/CS-1.3#1]
- Your code has some good spacing and comments. One place where I wished there was a comment is on line 38 and 39 in bases.py. Those lines do a lot for the function, and it might be hard for someone to understand what is going on and why if they have never seen it before.
- It seems that your string search functions share a lot of the same code. I recommend refactoring it so that two of the function call the third one. In addition, it seems that you are using string splices, which is okay, but string splices increase the space complexity of your code (splices create a copy of the string), so I would recommend refactoring it.
- One small thing I wanted to point out was that you converted the number string to a list in your decode function. In Python, you can use strings as if they were lists, so I recommend trying to not convert the string to a list, and seeing if it still works.

**Comment by GirugaCode** [comment]
Thank you for the feedback, Ansel! I took the time and made the necessary adjustments.
