### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [GirugaCode/CS-1.3#2]
- Be careful with your big O notation on built in methods; in ArrayQueue dequeue, deleting the first element in a list is O(n), not O(1). You can read more in the Python [docs](https://docs.python.org/2/tutorial/datastructures.html#using-lists-as-queues). 
- In your Set, watch out for un-optimizing code. Wherever you're checking if an item is in a set, you are moving it from a hash table into a list and looking into the list (O(n) complexity worst case). You can just use a method on your hash table to see if the item is in the set (close to, if not, O(1) complexity).
- Your set tests are pretty good the way they currently are, but you might consider varying the input to use integers or multi-character strings, as I have already seen this break someone's code.

**Comment by GirugaCode** [comment]
Thank you agian Ansel for the feedback! I just implemented the changes in my most recent commit.
