### ISSUE TITLE
Feedback on Palindromes and String Searching Algorithms

### ISSUE THREAD

**Issue by fchikwekwe** [GirugaCode/CS-1.3#4]
Your palindromes function is pretty good. Its good that instead of trying to remove punctuation and whitespace from the string, you check each spot for non-letter values. Another improvement you can make is to lower each letter as you iterate instead of lowering them all up front. 

Your time complexity analysis for `find_index` and `find_all_indexes` makes sense, but I don't think that it is quite correct. Also, you are still duplicating code throughout your `strings.py` file.

**Comment by GirugaCode** [comment]
Thank you for the feedback Faith!
