### ISSUE TITLE
Feedback: Trees & Tree Traversals

### ISSUE THREAD

**Issue by anselb** [GirugaCode/CS-1.3#7]
- Your binary tree runs well for the most part, but your `_find_parent_node_recursive` method fails some tests. If you try and run it in your `insert` method (replace its iterative counterpart), you will see it fails tests.
- The bug occurs when you handle the first base case. You return `None`, but you should return `parent`. The goal of this first `if` statement is not to only handle the case that the root does not exist. It also handles the case when you are trying to insert a node that doesn't exist yet. You can imagine that this function traverses to the spot where a node should be inserted (it does this by traversing until it hits a `None`), and then returning the parent of this empty spot (the empty spot is None). Returning `parent` handles the no-root case because parent is first set to None as a default argument (and it will return when node, or self.root, is None), and it handles this new case when a new node needs to be inserted.

**Comment by GirugaCode** [comment]
Thank you for the feedback! I fixed it and got it!
